import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { RFPercentage } from "react-native-responsive-fontsize";

const Theme = {
  instaPrimary: "#0064E0",
  red: "red",
  white: "white",
  green: "green",
  btnGrey: "#FFFFFFCC",
  btnblue: "#0047AB",
  primary: "#d75f4f",
  secondary: "#fffcf8",
  gold: "#ada11f",
  DarkestBlue: "#2F2E41",
  lightGrey: "#fffcf8",
  blueish: "#4472c4",
  grey: "#DCDCDC",
  txtWhite: "#ffffff",
  btnGrey: "#FFFFFFCC",
  lightWhite: "#F5F5FFD1",
  borderColor: "#EBEBEB",
  newGrey: "#C7C7C7",
  hardBlack: "#000015D9",
  frozey: "#BDC1FF",
  txtBlue: "blue",
  orange: "#FCA82F",
  heavyRed: "#EC1C24",
  lightYellow: "#F9EDDC",
  lightFrozey: "#CAF3F8",
  greish: "#4F4F4F",
  lightGreish: "#C4C4C4",
  green: "green",
  parrot: "#03FF3B",
  hardPurple: "#62349E",
  purple: "#431D75",
  lightPink: "#F5EEFF",
  sky: "#6BDAE6",
  yellow: "#FEF638",
  placeholderCol: "grey",
  instagram: "Fontspring-DEMO-blue_vinyl_bold_ps_ot",
  white: "white",
  blue: "#5978ff",
  black: "black",
  txtBlack: "black",
  iconCol: "#D1D1D1",
  iconSize: 26,
  iconSizeLarge: 35,
  iconSizeExtraLarge: 45,
  iconSizeSm: 20,
  iconSizeExSm: 12,
  bold: "bold",
  errorColor: "red",
  gray1: "#525455",
  txtTiny: RFPercentage(1.3),
  txtSmallest: RFPercentage(1.8),
  txtSmallest1: RFPercentage(1.5),
  txtSmall: RFPercentage(2),
  txtMedium: RFPercentage(2.5),
  txtLarge: RFPercentage(3),
  txtExtraLarge: RFPercentage(3.5),
  align: "center",
  wp,
  hp,
  RFPercentage,
  shorterWidth: wp("85%"),
  width: wp("95%"),
  shadow: {
    shadowColor: "blue",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  fontInstaRegular: "blue_vinyl_regular_ps_ot",
  fontInstaBold: "blue_vinyl_bold_ps_ot",
};

export default Theme;
