const postInfo = [
  {
    id: "insta_post1111",
    postTitle: "Mr_john",
    postPersonImage: require("../../Assets/Images/men.jpg"),
    postImage: require("../../Assets/Images/white1.jpg"),
    postImage1: require("../../Assets/Images/cat.jpg"),
    postImages: [
      require("../../Assets/Images/white1.jpg"),
      require("../../Assets/Images/girl.jpg"),
      require("../../Assets/Images/white1.jpg"),
    ],
    likes: 765,
    isLiked: false,
    price: "¥2500",
    price2: "¥3500",
    about: "Fruits, Vegetables, Peanut ",
    about1: "2 Years Old",
    about2: "wow dog is beautiful i want to buy",
    isVideo: true,
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  },
  {
    id: "insta_post1112",
    postTitle: "Alexandra_",
    postPersonImage: require("../../Assets/Images/girl.jpg"),
    postImage: require("../../Assets/Images/white2.jpg"),
    postImages: [
      require("../../Assets/Images/post15.jpg"),
      require("../../Assets/Images/post2.jpg"),
      require("../../Assets/Images/girl.jpg"),
    ],
    likes: 345,
    isLiked: false,
    price: "¥8000",
    price2: "¥9500",
    about: "#pets #pet #dogs #petsofinstagram #dog #dogsofinstagram #cats  ",
    about: "Chicken and Beef",
    about1: "1 Years Old",
  },
  {
    id: "insta_post1113",
    postTitle: "Tom",
    postPersonImage: require("../../Assets/Images/dog.jpg"),
    postImage: require("../../Assets/Images/cat1.jpg"),
    postImages: [
      require("../../Assets/Images/post3.jpg"),
      require("../../Assets/Images/post4.jpg"),
    ],
    likes: 734,
    isLiked: false,
    price: "¥3000",
    price2: "¥4500",
    about: "#pets #pet #dogs #petsofinstagram #dog #dogsofinstagram #cats",
    about: "Fruits, Vegetables, Peanut Butter",
    about1: "5 Years Old",
  },
  {
    id: "insta_post1114",
    postTitle: "The_Groot",
    postPersonImage: require("../../Assets/Images/menpuppy.jpg"),
    postImage: require("../../Assets/Images/cat2.jpg"),
    postImages: [
      require("../../Assets/Images/cat2.jpg"),
      require("../../Assets/Images/menpuppy.jpg"),
    ],
    likes: 875,
    isLiked: false,
    price: "¥5000",
    price2: "¥6500",
    about: "#pets #pet #dogs #petsofinstagram #dog #dogsofinstagram #cats",
    about: "Fruits, Vegetables, Peanut Butter",
    about1: "6 Years Old",
    isVideo: true,
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  },
  {
    id: "insta_post1115",
    postTitle: "D-O-G",
    postPersonImage: require("../../Assets/Images/menpuppy2.jpg"),
    postImage: require("../../Assets/Images/lebra.jpg"),
    postImages: [
      require("../../Assets/Images/post7.jpg"),
      require("../../Assets/Images/post8.jpg"),
    ],
    likes: 875,
    isLiked: false,
    price: "¥8000",
    price2: "¥8500",
    about: "#pets #pet #dogs #petsofinstagram #dog #dogsofinstagram #cats",
    about: "Fruits, Vegetables, Peanut Butter",
    about1: "6 Years Old",
  },
  {
    id: "insta_post1116",
    postTitle: "The_c_a_t",
    postPersonImage: require("../../Assets/Images/menpuppy3.jpg"),
    postImage: require("../../Assets/Images/lebra2.jpg"),
    postImages: [
      require("../../Assets/Images/post9.jpg"),
      require("../../Assets/Images/post10.jpg"),
    ],
    likes: 875,
    isLiked: false,
    price: "¥4000",
    price2: "¥4500",
    about: "#pets #pet #dogs #petsofinstagram #dog #dogsofinstagram #cats",
    about: "Fruits, Vegetables, Peanut Butter",
    about1: "6 Years Old",
    isVideo: true,
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  },
  {
    id: "insta_post1117",
    postTitle: "The_pet",
    postPersonImage: require("../../Assets/Images/menpuppy4.jpg"),
    postImage: require("../../Assets/Images/kity1.jpg"),
    postImages: [
      require("../../Assets/Images/post11.jpg"),
      require("../../Assets/Images/post12.jpg"),
    ],
    likes: 875,
    isLiked: false,
    price: "¥10000",
    price2: "¥15000",
    about: "#pets #pet #dogs #petsofinstagram #dog #dogsofinstagram #cats",
    about: "Fruits, Vegetables, Peanut Butter",
    about1: "6 Years Old",
  },
  {
    id: "insta_post1118",
    postTitle: "groite",
    postPersonImage: require("../../Assets/Images/menpuppy5.jpg"),
    postImage: require("../../Assets/Images/kitty2.jpg"),
    postImages: [
      require("../../Assets/Images/post13.jpg"),
      require("../../Assets/Images/post14.jpg"),
    ],
    likes: 875,
    isLiked: false,
    price: "¥15000",
    price2: "¥16500",
    about: "#pets #pet #dogs #petsofinstagram #dog #dogsofinstagram #cats",
    about: "Fruits, Vegetables, Peanut Butter",
    about1: "6 Years Old",
  },
  {
    id: "insta_post1119",
    postTitle: "jammy",
    postPersonImage: require("../../Assets/Images/menpuppy6.jpg"),
    postImage: require("../../Assets/Images/kitty4.jpg"),
    postImages: [
      require("../../Assets/Images/parrot.jpg"),
      require("../../Assets/Images/profile2.jpg"),
    ],
    likes: 875,
    isLiked: false,
    price: "¥9000",
    price2: "¥10500",
    about: "#pets #pet #dogs #petsofinstagram #dog #dogsofinstagram #cats",
    about: "Fruits, Vegetables, Peanut Butter",
    about1: "6 Years Old",
  },
];

export default postInfo;
